"""Add Metadata Validation

Revision ID: 03b96e5299a9
Revises: 43a1abb3a2c8
Create Date: 2026-07-20 12:29:22.383750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b96e5299a9'
down_revision: Union[str, Sequence[str], None] = '43a1abb3a2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_validations',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=False),
    sa.Column('validation_value', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['metadata_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_validations_field_id'), 'metadata_validations', ['field_id'], unique=False)
    op.create_index(op.f('ix_metadata_validations_id'), 'metadata_validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_validations_id'), table_name='metadata_validations')
    op.drop_index(op.f('ix_metadata_validations_field_id'), table_name='metadata_validations')
    op.drop_table('metadata_validations')
    # ### end Alembic commands ###
