"""Add Metadata Field

Revision ID: 293dfab9c35e
Revises: c72eee08bb4a
Create Date: 2026-07-20 12:22:40.005087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293dfab9c35e'
down_revision: Union[str, Sequence[str], None] = 'c72eee08bb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_fields',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('control_type', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['metadata_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_fields_id'), 'metadata_fields', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_fields_module_id'), 'metadata_fields', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_fields_module_id'), table_name='metadata_fields')
    op.drop_index(op.f('ix_metadata_fields_id'), table_name='metadata_fields')
    op.drop_table('metadata_fields')
    # ### end Alembic commands ###
