"""Add Metadata Relationship

Revision ID: 43a1abb3a2c8
Revises: 293dfab9c35e
Create Date: 2026-07-20 12:26:31.511175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a1abb3a2c8'
down_revision: Union[str, Sequence[str], None] = '293dfab9c35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_relationships',
    sa.Column('source_module_id', sa.Integer(), nullable=False),
    sa.Column('target_module_id', sa.Integer(), nullable=False),
    sa.Column('source_field', sa.String(length=100), nullable=False),
    sa.Column('target_field', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_module_id'], ['metadata_modules.id'], ),
    sa.ForeignKeyConstraint(['target_module_id'], ['metadata_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_relationships_id'), 'metadata_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_relationships_id'), table_name='metadata_relationships')
    op.drop_table('metadata_relationships')
    # ### end Alembic commands ###
