"""Add Metadata Workflow

Revision ID: 896d79b50544
Revises: 97bf39969d3f
Create Date: 2026-07-21 05:24:40.456088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896d79b50544'
down_revision: Union[str, Sequence[str], None] = '97bf39969d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_workflows',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=150), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=150), nullable=False),
    sa.Column('approver_role', sa.String(length=100), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['metadata_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_workflows_id'), 'metadata_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_workflows_module_id'), 'metadata_workflows', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_workflows_module_id'), table_name='metadata_workflows')
    op.drop_index(op.f('ix_metadata_workflows_id'), table_name='metadata_workflows')
    op.drop_table('metadata_workflows')
    # ### end Alembic commands ###
