"""Add Metadata Template

Revision ID: ceabfa5236d7
Revises: ff06bf4465e6
Create Date: 2026-07-21 05:41:13.289177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceabfa5236d7'
down_revision: Union[str, Sequence[str], None] = 'ff06bf4465e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_templates',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=150), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['metadata_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_templates_id'), 'metadata_templates', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_templates_module_id'), 'metadata_templates', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_templates_module_id'), table_name='metadata_templates')
    op.drop_index(op.f('ix_metadata_templates_id'), table_name='metadata_templates')
    op.drop_table('metadata_templates')
    # ### end Alembic commands ###
