"""Add Metadata Report

Revision ID: ff06bf4465e6
Revises: 8c96d21ca97f
Create Date: 2026-07-21 05:38:08.474390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff06bf4465e6'
down_revision: Union[str, Sequence[str], None] = '8c96d21ca97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_dashboards',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_name', sa.String(length=150), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('data_source', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['metadata_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_dashboards_id'), 'metadata_dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_dashboards_module_id'), 'metadata_dashboards', ['module_id'], unique=False)
    op.create_table('metadata_reports',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('query_definition', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['metadata_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_reports_id'), 'metadata_reports', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_reports_module_id'), 'metadata_reports', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_reports_module_id'), table_name='metadata_reports')
    op.drop_index(op.f('ix_metadata_reports_id'), table_name='metadata_reports')
    op.drop_table('metadata_reports')
    op.drop_index(op.f('ix_metadata_dashboards_module_id'), table_name='metadata_dashboards')
    op.drop_index(op.f('ix_metadata_dashboards_id'), table_name='metadata_dashboards')
    op.drop_table('metadata_dashboards')
    # ### end Alembic commands ###
